# Generated by Django 3.1.7 on 2023-03-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
